src/GotTable.Web/Controllers/DailyBookingListController.cs
using GotTable.DAO.Reports;
using GotTable.Library.OperationExceptionLogs;
using GotTable.Library.Reports;
using GotTable.Library.Reports.Criterias;
using GotTable.Web.Filters;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GotTable.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Permission(allowedRoles)]
    public sealed class DailyBookingListController : UserBaseController
    {
        /// <summary>
        /// 
        /// </summary>
        private const string allowedRoles = "SuperAdmin, SalesAdmin";

        /// <summary>
        /// 
        /// </summary>
        private readonly IReportList<DailyBookingDAO, DailyBookingListCriteria> reportList;

        public DailyBookingListController(IReportList<DailyBookingDAO, DailyBookingListCriteria> reportList, IOperationExceptionLog operationExceptionLog) : base(operationExceptionLog)
        {
            this.reportList = reportList;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="bookingDate"></param>
        /// <param name="currentPage"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Index(string bookingDate = default, int currentPage = 0, int pageSize = 10)
        {
            DateTime dtBookingDate = String.IsNullOrEmpty(bookingDate) ? DateTime.Now : DateTime.ParseExact(bookingDate, "MM-dd-yyyy", null);
            var criteria = new DailyBookingListCriteria(dtBookingDate, currentPage, pageSize);
            var dailyBookings = await reportList.Get(criteria);
            ViewBag.SelectedDate = bookingDate;
            return View(dailyBookings);
        }
    }
}

src/GotTable.Web/Views/DailyBookingList/Index.cshtml
@model IEnumerable<GotTable.DAO.Reports.DailyBookingDAO>
@using GotTable.Web.Views.DailyBookingList;
@{
    ViewBag.Title = "Index";
    ViewBag.ActiveMenu = "Reports";
    ViewBag.ActiveSubMenu = "DailyBookings";
    Layout = "~/Views/Shared/IndexViewLayout.cshtml"; 
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".datepicker").datepicker({
            autoclose: true,
            format: 'mm-dd-yyyy',
            pickerPosition: "bottom-right",
        });

        $(".datepicker").change(function () {
            var url = '@Url.Action("Index", "DailyBookingList", new { @bookingDate = "__bookingDate__" })';
            window.location.href = url.replace("__bookingDate__", $(this).val());
        });
    });
</script>
<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#">Home</a> </li>
            <li><i class="icon-settings"></i>Daily booking</li>
        </ul>
    </div>
    <div class="page-content">
        <div class="addheader">
            <div class="col-lg-9">
                <h2>Daily Booking</h2>
            </div>
            <div class="col-lg-3" style="margin-top:3px;">
                <input type="text" class="form-control datepicker" readonly value='@ViewBag.SelectedDate' />
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @IndexResources.BranchName
                                </th>
                                <th>
                                    @IndexResources.State
                                </th>
                                <th>
                                    @IndexResources.BranchCity
                                </th>
                                <th>
                                    @IndexResources.Zip
                                </th>
                                <th>
                                    @IndexResources.UserName
                                </th>
                                <th>
                                    @IndexResources.PhoneNumber
                                </th>
                                <th>
                                    @IndexResources.BookingType
                                </th>
                                <th>
                                    @IndexResources.BookingDateTime
                                </th>
                                <th>
                                    @IndexResources.BookingCreationDate
                                </th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            var formatedBookingDateTime = string.Empty;
                            formatedBookingDateTime = DateTime.ParseExact(item.BookingDate + " " + item.BookingTime, "MM-dd-yyyy HH:mm", null).ToString("dd-MM-yyyy hh:mm tt");
                            <tr>
                                <td>
                                    @item.BranchName
                                </td>
                                <td>
                                    @item.BranchState
                                </td>
                                <td>
                                    @item.BranchCity
                                </td>
                                <td>
                                    @item.BranchZipCode
                                </td>
                                <td>
                                    @item.UserName
                                </td>
                                <td>
                                    @item.PhoneNumber
                                </td>
                                <td>
                                    @item.BookingType.ToString()
                                </td>
                                <td>
                                    <span>@formatedBookingDateTime</span>
                                </td>
                                <td>
                                    @item.CreatedDate
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>